stages:
  prepare:
    cmd: python data_preparation.py
    deps:
      - data/iris.csv
      - data_preparation.py
    outs:
      - data/iris_prepared.csv

  train:
    cmd: python train.py
    deps:
      - data/iris_prepared.csv
      - train.py
    outs:
      - data/trained_model.pkl

  evaluate:
    cmd: python eval.py
    deps:
      - data/iris_prepared.csv
      - eval.py
      - data/trained_model.pkl